// cms-fe/src/pages/Seats.tsx
import { useEffect, useState } from 'react';
import { api } from '../api/client';
import type { Seat, Screen, Theater } from '../types';
import { Card, CardHeader } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Select } from '../components/ui/Select';
import { Table, TableHead, TableBody, TableRow, Th, Td } from '../components/ui/Table';

const SEAT_TYPE_OPTIONS = [
  { value: 'standard', label: 'Standard' },
  { value: 'premium', label: 'Premium' },
  { value: 'wheelchair', label: 'Wheelchair' },
];

const SEAT_TYPE_STYLE: Record<Seat['type'], string> = {
  standard: 'bg-zinc-600 hover:bg-zinc-500',
  premium: 'bg-cinema-gold/80 text-cinema-dark hover:bg-cinema-gold',
  wheelchair: 'bg-sky-600 hover:bg-sky-500',
};

export function Seats() {
  const [theaters, setTheaters] = useState<Theater[]>([]);
  const [screenId, setScreenId] = useState<string>('');
  const [seats, setSeats] = useState<Seat[]>([]);
  const [loading, setLoading] = useState(true);
  const [seatsLoading, setSeatsLoading] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState({ row: 'A', seatNumber: 1, type: 'standard' as Seat['type'], isActive: true });
  const [saving, setSaving] = useState(false);

  const screens: { screen: Screen; theater: Theater }[] = theaters.flatMap((t) =>
    t.screens.map((s) => ({ screen: s, theater: t }))
  );
  const selectedScreen = screens.find((s) => s.screen.id === screenId);

  useEffect(() => {
    api.getTheaters().then((data) => {
      setTheaters(data);
      if (data.length && data[0].screens.length && !screenId) {
        setScreenId(data[0].screens[0].id);
      }
      setLoading(false);
    });
  }, []);

  useEffect(() => {
    if (!screenId) {
      setSeats([]);
      return;
    }
    setSeatsLoading(true);
    api.getSeatsByScreen(screenId).then((data) => {
      setSeats(data);
      setSeatsLoading(false);
    });
  }, [screenId]);

  const handleAddSeat = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!screenId) return;
    setSaving(true);
    try {
      const created = await api.createSeat({
        screenId,
        row: form.row.trim().toUpperCase() || 'A',
        seatNumber: form.seatNumber,
        type: form.type,
        isActive: form.isActive,
      });
      setSeats((prev) => [...prev, created].sort((a, b) => a.row.localeCompare(b.row) || a.seatNumber - b.seatNumber));
      setForm((f) => ({ ...f, seatNumber: f.seatNumber + 1 }));
    } finally {
      setSaving(false);
    }
  };

  const handleUpdateSeat = async (id: string, data: Partial<Seat>) => {
    const updated = await api.updateSeat(id, data);
    if (updated) {
      setSeats((prev) =>
        prev.map((s) => (s.id === id ? { ...s, ...updated } : s))
      );
      setEditingId(null);
    }
  };

  const handleDeleteSeat = async (id: string) => {
    if (!confirm('Remove this seat?')) return;
    const ok = await api.deleteSeat(id);
    if (ok) setSeats((prev) => prev.filter((s) => s.id !== id));
  };

  const rows = Array.from(new Set(seats.map((s) => s.row))).sort();
  const maxCol = Math.max(0, ...seats.map((s) => s.seatNumber));
  const seatMap = new Map(seats.map((s) => [`${s.row}-${s.seatNumber}`, s]));

  return (
    <div className="p-8">
      <div className="mb-8">
        <h1 className="font-display font-bold text-2xl text-zinc-100">Seats</h1>
        <p className="text-cinema-muted mt-1">Manage seats per screen</p>
      </div>

      {loading ? (
        <div className="text-cinema-muted">Loading theaters...</div>
      ) : (
        <>
          <Card className="mb-6">
            <label className="block text-sm font-medium text-zinc-300 mb-2">Screen</label>
            <select
              value={screenId}
              onChange={(e) => setScreenId(e.target.value)}
              className="w-full max-w-md px-3 py-2 rounded-lg bg-cinema-dark border border-cinema-border text-zinc-100 focus:outline-none focus:ring-2 focus:ring-cinema-gold/50"
            >
              <option value="">Select a screen</option>
              {screens.map(({ screen, theater }) => (
                <option key={screen.id} value={screen.id}>
                  {theater.name} — {screen.name} ({screen.capacity} seats)
                </option>
              ))}
            </select>
          </Card>

          {screenId && (
            <>
              <Card className="mb-6">
                <CardHeader
                  title="Add seat"
                  subtitle={`Add a new seat to ${selectedScreen?.screen.name ?? 'this screen'}`}
                />
                <form onSubmit={handleAddSeat} className="flex flex-wrap items-end gap-4">
                  <div className="w-24">
                    <label className="block text-xs text-cinema-muted mb-1">Row</label>
                    <Input
                      value={form.row}
                      onChange={(e) => setForm((f) => ({ ...f, row: e.target.value }))}
                      placeholder="A"
                      maxLength={2}
                    />
                  </div>
                  <div className="w-24">
                    <label className="block text-xs text-cinema-muted mb-1">Number</label>
                    <Input
                      type="number"
                      min={1}
                      value={form.seatNumber}
                      onChange={(e) =>
                        setForm((f) => ({ ...f, seatNumber: Number(e.target.value) || 1 }))
                      }
                    />
                  </div>
                  <div className="w-36">
                    <label className="block text-xs text-cinema-muted mb-1">Type</label>
                    <Select
                      options={SEAT_TYPE_OPTIONS}
                      value={form.type}
                      onChange={(e) =>
                        setForm((f) => ({ ...f, type: e.target.value as Seat['type'] }))
                      }
                    />
                  </div>
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="newActive"
                      checked={form.isActive}
                      onChange={(e) => setForm((f) => ({ ...f, isActive: e.target.checked }))}
                      className="rounded border-cinema-border bg-cinema-dark text-cinema-gold"
                    />
                    <label htmlFor="newActive" className="text-sm text-zinc-300">Active</label>
                  </div>
                  <Button type="submit" loading={saving}>
                    Add seat
                  </Button>
                </form>
              </Card>

              <Card className="mb-6">
                <CardHeader
                  title="Seat layout"
                  subtitle={`${seats.length} seat(s)`}
                />
                {seatsLoading ? (
                  <div className="py-8 text-center text-cinema-muted">Loading seats...</div>
                ) : seats.length === 0 ? (
                  <div className="py-8 text-center text-cinema-muted">
                    No seats yet. Add seats above.
                  </div>
                ) : (
                  <div className="overflow-x-auto">
                    <div className="inline-block p-4 bg-cinema-dark rounded-lg">
                      <div className="flex gap-0.5 mb-2">
                        <span className="w-6 text-xs text-cinema-muted" />
                        {Array.from({ length: maxCol }, (_, i) => (
                          <span
                            key={i}
                            className="w-7 text-center text-xs text-cinema-muted"
                          >
                            {i + 1}
                          </span>
                        ))}
                      </div>
                      {rows.map((row) => (
                        <div key={row} className="flex gap-0.5 items-center mb-1">
                          <span className="w-6 text-xs font-medium text-cinema-muted">{row}</span>
                          <div className="flex gap-0.5">
                            {Array.from({ length: maxCol }, (_, i) => {
                              const num = i + 1;
                              const seat = seatMap.get(`${row}-${num}`);
                              if (!seat)
                                return (
                                  <span
                                    key={`${row}-${num}`}
                                    className="w-7 h-7 rounded bg-cinema-border/30"
                                  />
                                );
                              return (
                                <span
                                  key={seat.id}
                                  className={`w-7 h-7 rounded flex items-center justify-center text-xs font-medium ${SEAT_TYPE_STYLE[seat.type]} ${!seat.isActive ? 'opacity-40' : ''}`}
                                  title={`${row}${num} — ${seat.type}`}
                                >
                                  {seat.isActive ? num : '—'}
                                </span>
                              );
                            })}
                          </div>
                        </div>
                      ))}
                    </div>
                    <div className="flex gap-4 mt-4 text-xs text-cinema-muted">
                      <span className="flex items-center gap-1">
                        <span className="w-4 h-4 rounded bg-zinc-600" /> Standard
                      </span>
                      <span className="flex items-center gap-1">
                        <span className="w-4 h-4 rounded bg-cinema-gold/80" /> Premium
                      </span>
                      <span className="flex items-center gap-1">
                        <span className="w-4 h-4 rounded bg-sky-600" /> Wheelchair
                      </span>
                    </div>
                  </div>
                )}
              </Card>

              <Card>
                <CardHeader title="All seats (table)" subtitle="Edit type or deactivate" />
                {seatsLoading ? (
                  <div className="py-8 text-center text-cinema-muted">Loading...</div>
                ) : (
                  <Table>
                    <TableHead>
                      <TableRow>
                        <Th>Row</Th>
                        <Th>Number</Th>
                        <Th>Type</Th>
                        <Th>Status</Th>
                        <Th className="text-right">Actions</Th>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {seats.map((seat) => (
                        <TableRow key={seat.id}>
                          <Td className="font-medium">{seat.row}</Td>
                          <Td>{seat.seatNumber}</Td>
                          <Td>
                            {editingId === seat.id ? (
                              <Select
                                options={SEAT_TYPE_OPTIONS}
                                value={seat.type}
                                onChange={(e) =>
                                  handleUpdateSeat(seat.id, {
                                    type: e.target.value as Seat['type'],
                                  })
                                }
                                onBlur={() => setEditingId(null)}
                                className="w-32"
                              />
                            ) : (
                              <span
                                className={`inline-flex px-2 py-0.5 rounded text-xs ${SEAT_TYPE_STYLE[seat.type]}`}
                              >
                                {seat.type}
                              </span>
                            )}
                          </Td>
                          <Td>
                            {editingId === seat.id ? (
                              <input
                                type="checkbox"
                                checked={seat.isActive}
                                onChange={(e) =>
                                  handleUpdateSeat(seat.id, { isActive: e.target.checked })
                                }
                                className="rounded border-cinema-border bg-cinema-dark text-cinema-gold"
                              />
                            ) : (
                              <span
                                className={`inline-flex px-2 py-0.5 rounded text-xs ${
                                  seat.isActive
                                    ? 'bg-emerald-500/20 text-emerald-400'
                                    : 'bg-zinc-500/20 text-zinc-400'
                                }`}
                              >
                                {seat.isActive ? 'Active' : 'Inactive'}
                              </span>
                            )}
                          </Td>
                          <Td className="text-right">
                            {editingId === seat.id ? (
                              <button
                                type="button"
                                onClick={() => setEditingId(null)}
                                className="text-cinema-muted hover:text-zinc-300 text-sm"
                              >
                                Done
                              </button>
                            ) : (
                              <>
                                <button
                                  type="button"
                                  onClick={() => setEditingId(seat.id)}
                                  className="text-cinema-gold hover:underline mr-3"
                                >
                                  Edit
                                </button>
                                <button
                                  type="button"
                                  onClick={() => handleDeleteSeat(seat.id)}
                                  className="text-red-400 hover:underline"
                                >
                                  Delete
                                </button>
                              </>
                            )}
                          </Td>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                )}
              </Card>
            </>
          )}
        </>
      )}
    </div>
  );
}

// src/views/Seats.vue
<template>
  <div class="p-8">
    <div class="mb-8">
      <h1 class="font-display font-bold text-2xl text-gray-800">Seats</h1>
      <p class="text-cinema-muted mt-1">Manage seats per screen</p>
    </div>

    <div v-if="loading" class="text-cinema-muted">Loading theaters...</div>
    <template v-else>
      <Card class="mb-6">
        <label class="block text-sm font-medium text-gray-700 mb-2">Screen</label>
        <select
          v-model="screenId"
          class="w-full max-w-md px-3 py-2 rounded-lg bg-cinema-panel border border-cinema-border text-gray-800 focus:outline-none focus:ring-2 focus:ring-cinema-gold/40 shadow-sm"
        >
          <option value="">Select a screen</option>
          <option v-for="{ screen, theater } in screens" :key="screen.id" :value="screen.id">
           {{ theater.name }} - {{ screen.name }} - {{ screen.capacity }} seats
          </option>
        </select>
      </Card>

      <template v-if="screenId">
        <Card class="mb-6">
          <CardHeader title="Seat layout" :subtitle="`${seats.length} seat(s)`" />
          <div v-if="seatsLoading" class="py-8 text-center text-cinema-muted">Loading seats...</div>
          <div v-else-if="seats.length === 0" class="py-8 text-center text-cinema-muted">
            No seats yet. Add seats above.
          </div>
          <div v-else class="overflow-x-auto">
            <div class="inline-block p-4 bg-cinema-surface rounded-lg border border-cinema-border">
              <div class="flex gap-0.5 mb-2">
                <span class="w-6 text-xs text-cinema-muted" />
                <span
                  v-for="i in maxCol"
                  :key="i"
                  class="w-7 text-center text-xs text-cinema-muted"
                >
                  {{ i }}
                </span>
              </div>
              <div v-for="row in rows" :key="row" class="flex gap-0.5 items-center mb-1">
                <span class="w-6 text-xs font-medium text-cinema-muted">{{ row }}</span>
                <div class="flex gap-0.5">
                  <template v-for="num in maxCol" :key="`${row}-${num}`">
                    <span
                      v-if="!seatMap.get(`${row}-${num}`)"
                      class="w-7 h-7 rounded bg-gray-200"
                    />
                    <span
                      v-else
                      :class="[
                        'w-7 h-7 rounded flex items-center justify-center text-xs font-medium',
                        SEAT_TYPE_STYLE[seatMap.get(`${row}-${num}`)!.type],
                        !seatMap.get(`${row}-${num}`)?.isActive ? 'opacity-40' : '',
                      ]"
                      :title="`${row}${num} — ${seatMap.get(`${row}-${num}`)?.type}`"
                    >
                      {{ seatMap.get(`${row}-${num}`)?.isActive ? num : '—' }}
                    </span>
                  </template>
                </div>
              </div>
            </div>
            <div class="flex gap-4 mt-4 text-xs text-cinema-muted">
              <span class="flex items-center gap-1"><span class="w-4 h-4 rounded bg-gray-400" /> Standard</span>
              <span class="flex items-center gap-1"><span class="w-4 h-4 rounded bg-cinema-gold" /> Premium</span>
              <span class="flex items-center gap-1"><span class="w-4 h-4 rounded bg-sky-500" /> Wheelchair</span>
            </div>
          </div>
        </Card>

        <Card>
          <CardHeader title="All seats (table)" subtitle="Edit seat type or remove seat" />
          <div v-if="seatsLoading" class="py-8 text-center text-cinema-muted">Loading...</div>
          <template v-else>
            <div class="overflow-y-auto max-h-96 rounded-lg border border-cinema-border">
              <table class="text-sm text-left">
                <thead class="bg-cinema-surface text-cinema-muted uppercase text-xs sticky top-0">
                  <tr>
                    <th class="px-4 py-3 font-medium">Row</th>
                    <th class="px-4 py-3 font-medium">Number</th>
                    <th class="px-4 py-3 font-medium">Type</th>                  
                    <th class="px-4 py-3 font-medium text-right">Actions</th>
                  </tr>
                </thead>
                <tbody class="divide-y divide-cinema-border">
                  <tr
                    v-for="seat in seats"
                    :key="seat.id"
                    class="bg-cinema-panel hover:bg-cinema-surface/80 transition-colors"
                  >
                    <td class="px-4 py-3 font-medium">{{ seat.row }}</td>
                    <td class="px-4 py-3">{{ seat.seatNumber }}</td>
                    <td class="px-4 py-3">
                      <Select
                        v-if="editingId === seat.id"
                        :model-value="seat.type"
                        :options="SEAT_TYPE_OPTIONS"
                        class="w-32"
                        @update:model-value="(v: string) => handleUpdateSeat(seat.id, { type: v as Seat['type'] })"
                        @blur="editingId = null"
                      />
                      <span
                        v-else
                        :class="['inline-flex px-2 py-0.5 rounded text-xs', SEAT_TYPE_STYLE[seat.type]]"
                      >
                        {{ seat.type }}
                      </span>
                    </td>

                    <td class="px-4 py-3 text-right">
                      <template v-if="editingId === seat.id">
                        <button type="button" class="text-cinema-muted hover:text-gray-700 text-sm" @click="editingId = null">
                          Done
                        </button>
                      </template>
                      <template v-else>
                        <button type="button" class="text-cinema-gold hover:underline mr-3" @click="editingId = seat.id">
                          Edit
                        </button>
                        <button type="button" class="text-red-600 hover:underline" @click="handleDeleteSeat(seat.id)">
                          Delete
                        </button>
                      </template>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </template>
        </Card>
      </template>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, watch } from 'vue'
import type { Seat, Theater } from '../types'
import { api } from '../api/client'
import Card from '../components/ui/Card.vue'
import CardHeader from '../components/ui/CardHeader.vue'
import Select from '../components/ui/Select.vue'

const SEAT_TYPE_OPTIONS = [
  { value: 'STANDARD', label: 'Standard' },
  { value: 'PREMIUM', label: 'Premium' },
  { value: 'WHEELCHAIR', label: 'Wheelchair' },
]

const SEAT_TYPE_STYLE: Record<Seat['type'], string> = {
  STANDARD: 'bg-gray-400 text-white',
  PREMIUM: 'bg-cinema-gold text-white',
  WHEELCHAIR: 'bg-sky-500 text-white',
}

const theaters = ref<Theater[]>([])
const screenId = ref('')
const seats = ref<Seat[]>([])
const loading = ref(true)
const seatsLoading = ref(false)
const editingId = ref<string | null>(null)
const form = reactive({ row: 'A', seatNumber: 1, type: 'STANDARD' as Seat['type'], isActive: true })
const saving = ref(false)

const screens = computed(() =>
  theaters.value.flatMap((t) => t.screens.map((screen) => ({ screen, theater: t })))
)
const selectedScreen = computed(() => screens.value.find((s) => s.screen.id === screenId.value))
const rows = computed(() => [...new Set(seats.value.map((s) => s.row))].sort())
const maxCol = computed(() => Math.max(0, ...seats.value.map((s) => s.seatNumber)))
const seatMap = computed(() => new Map(seats.value.map((s) => [`${s.row}-${s.seatNumber}`, s])))

watch(theaters, (data) => {
  if (data.length && data[0].screens.length && !screenId.value) {
    screenId.value = data[0].screens[0].id
  }
}, { immediate: true })

watch(screenId, async (id) => {
  if (!id) {
    seats.value = []
    return
  }
  seatsLoading.value = true
  seats.value = await api.getSeatsByScreen(id)
  seatsLoading.value = false
}, { immediate: true })

async function loadTheaters() {
  theaters.value = await api.getTheaters()
  loading.value = false
}
loadTheaters()

async function handleAddSeat() {
  if (!screenId.value) return
  saving.value = true
  try {
    const created = await api.createSeat({
      screenId: screenId.value,
      row: form.row.trim().toUpperCase() || 'A',
      seatNumber: form.seatNumber,
      type: form.type,
      isActive: form.isActive,
    })
    seats.value = [...seats.value, created].sort((a, b) => a.row.localeCompare(b.row) || a.seatNumber - b.seatNumber)
    form.seatNumber++
  } finally {
    saving.value = false
  }
}

async function handleUpdateSeat(id: string, data: Partial<Seat>) {
  const updated = await api.updateSeat(id, data)
  if (updated) {
    seats.value = seats.value.map((s) => (s.id === id ? { ...s, ...updated } : s))
    editingId.value = null
  }
}

async function handleDeleteSeat(id: string) {
  if (!confirm('Remove this seat?')) return
  const ok = await api.deleteSeat(id)
  if (ok) seats.value = seats.value.filter((s) => s.id !== id)
}
</script>
